<?php

// Language definitions used in viewforum.php
$lang_forum = array(

'Forum subtitle'			=>	'%1$s neste fórum com detalhes de %2$s.',
'Search subtitle'			=>	'%1$s encontrados com detalhes de %2$s.',
'Topics'					=>	'Tópicos',
'topics'					=>	'tópicos',
'Reply'						=>	'Resposta',
'Replies'					=>	'Respostas',
'Forum'						=>	'Fórum',
'reply'						=>	'resposta',
'replies'					=>	'respostas',
'View'						=>	'Visualização',
'Views'						=>	'Visualizações',
'views'						=>	'visualizações',
'view'						=>	'visualização',
'Last post'					=>	'Último post',
'last post'					=>	'último post',
'Select topic'				=>	'Selecionar tópico: %s.',
'No replies info'			=>	'Sem informação de respostas',
'No views info'				=>	'Sem informações de visualizações',
'No lastpost info'			=>	'Sem informação de último post',
'by poster'					=>	'por %s',
'Item status'				=>	'%s:',
'Topic starter'				=>	'por <cite>%s</cite>',
'New posts'					=>	'Novos posts',
'Topic navigation'			=>	'( %s )',
'Location'					=>	'Encontrados no fórum: %s',
'Pages'						=>	'Páginas',
'Post topic'				=>	'Publicar novo tópico',
'Login to post'				=>	'Você deve %1$s ou %2$s para publicar um novo tópico',
'No permission'				=>	'Desculpe! sem permissão para publicar novos tópicos',
'Moved'						=>	'Movido',
'Sticky'					=>	'Fixado',
'Closed'					=>	'Fechado',
'Empty forum'				=>	'Fórum vazio',
'No topics'					=>	'Nenhum tópico foi publicado',
'First topic nag'			=>	'Seja o primeiro a publicar um tópico neste fórum.',
'You posted indicator'		=>	'·',
'Permalink forum'			=>	'Link permanente para este fórum.',
'Forum options'				=>	'Opções do fórum',
'Moderate forum'			=>	'Moderar o fórum',
'Mark forum read'			=>	'Marcar o fórum como lido',
'RSS forum feed'			=>	'Feed RSS do fórum',
'New posts info'			=>	'Ir para o primeiro post novo desde a sua última visita.',
'Unsubscribe'				=>	'Desinscrever-se',
'Subscribe'					=>	'Inscrever-se',
'Subscribe info'			=>	'Receber notificações de novos tópicos por e-mail.',

);
