<?php

// Definições da linguagem utilizada em search.php
$lang_search = array(

// Formulário de pesquisa
'No search permission'		=>	'Você não tem permissão para usar o recurso de pesquisa.',
'Search heading'			=>	'Pesquisar fóruns utilizando os seus critérios',
'Search flood'				=>	'Pelo menos %s segundos tem de passar entre pesquisas. Por favor, aguarde um pouco e tente procurar novamente.',
'Search legend'				=>	'Critérios de pesquisa',
'Results legend'			=>	'Resultados da pesquisa',
'Keywords info'				=>	'Você pode buscar por uma única palavra-chave ou por várias palavras-chave separadas por espaços.',
'Refine info'				=>	'Você pode usar <strong>E</strong>, <strong>ou</strong> e <strong>não</strong> para refinar suas buscas por palavra-chave.',
'Wildcard info'				=>	'Use o caractere universal <strong>*</strong> para palavra-chave ou nome de usuário corresponda parcialmente.',
'Forum default info'		=>	'Por padrão todos os fóruns são pesquisados. Você pode restringir a sua pesquisa, selecionando um ou mais fóruns para pesquisar.',
'Forum require info'		=>	'Você pode optar por procurar um ou mais fóruns. Você <strong>deve</strong> selecionar pelo menos um fórum para pesquisa.',
'Keyword search'			=>	'Palavra-chave ou palavras',
'Author search'				=>	'Autor nome de usuário',
'Forum search'				=>	'Selecione os fóruns de pesquisa',
'Forum search default'		=>	'Se não há fóruns selecionados então todos os fóruns serão pesquisados.',
'Forum search require'		=>	'Você deve selecionar pelo menos um fórum para pesquisa.',
'Sort by'					=>	'Classificar resultados por',
'Sort order'				=>	'Resultados ordem de classificação',
'Sort by post time'			=>	'Data de publicação',
'Sort by author'			=>	'Autor',
'Sort by subject'			=>	'Titulo',
'Sort by forum'				=>	'Fórum',
'Ascending'					=>	'Crescente',
'Descending'				=>	'Descendente',
'Display results'			=>	'Mostrar resultados',
'Show as topics'			=>	'Como tópicos',
'Show as posts'				=>	'Como os posts',
'Submit search'				=>	'Pesquisar',
'User defined search'		=>	'Busca definida pelo usuário',
'Advanced search'			=>	'Pesquisa avançada',
'Search in'					=>	'Procurar em',
'Message and subject'		=>	'Titulo do tópico e mensagem',
'Message only'				=>	'Apenas mensagens de texto',
'Topic only'				=>	'Titulo do Tópico',

// Resultados
'Search results'			=>	'Resultados da pesquisa',
'Topics with new'			=>	'Tópicos com novos posts',
'All Topics'				=>	'Mostrar todos os tópicos',
'Recently active topics'	=>	'Tópicos recentemente ativos',
'Unanswered topics'			=>	'Tópicos sem resposta',
'Subscriptions'				=>	'Subscreva',
'Forum subscriptions'		=>	'Subscreva este forum',
'Forums found'				=>	'Fóruns encontrados',
'Topics found'				=>	'Tópicos encontrados',
'Posts found'				=>	'Posts encontrados',
'Topics by'					=>	'Tópicos por %s',
'Posts by'					=>	'Posts por %s',
'Topics by user'			=>	'Tópicos por este usuário',
'Posts by user'				=>	'Mensagens deste usuário',
'Perform new search'		=>	'Realizar nova pesquisa',
'Search options'			=>	'Opções de pesquisa',
'Posted in'					=>	'Postado em ',
'No terms'					=>	'Você tem que escrever pelo menos uma palavra-chave e/ou o username de um autor para pesquisar.',
'No hits'					=>	'Sua busca não retornou resultados.',
'No user posts'				=>	'Não há mensagens deste utilizador neste fórum.',
'No user topics'			=>	'Não há tópicos deste utilizador neste fórum.',
'No subscriptions'			=>	'Não há tópicos subscritos.',
'No forum subscriptions'	=>	'Não existem fóruns subscritos.',
'No new posts'				=>	'Não há tópicos com novos posts desde sua última visita.',
'No recent posts'			=>	'Não há postagens feitas recentemente.',
'No unanswered'				=>	'Não há mensagens sem resposta neste fórum.',
'Go to post'				=>	'Ir para a publicação',
'Go to forum'				=>	'Ir para fórum',
'Go to topic'				=>	'Ir para o tópico',
'Go to profile'				=>	'Ir para o perfil de %s\'s'

);
